In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
import missingno
import warnings
warnings.filterwarnings("ignore")
import math, time, random, datetime
import featuretools as ft

In [2]:
dataset=pd.read_csv('weatherAUS.csv')
dataset.head(10)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,12/1/2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,12/2/2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,12/3/2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,12/4/2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,12/5/2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
5,12/6/2008,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,No
6,12/7/2008,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,No
7,12/8/2008,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,No
8,12/9/2008,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,Yes
9,12/10/2008,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,58.0,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,No

In [3]:
dataset.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,12/1/2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,12/2/2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,12/3/2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,12/4/2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,12/5/2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

# finding missing data

In [4]:
dataset.isna().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [6]:
dataset['Date'] = pd.to_datetime(dataset['Date'])
dataset['year'] = dataset['Date'].dt.year
dataset['month'] = dataset['Date'].dt.month
dataset['day'] = dataset['Date'].dt.day

In [7]:
#dataset.drop('Date', axis = 1, inplace = True)
dataset['Date'] = pd.to_datetime(dataset['Date']).dt.month
dataset.rename(columns={'Date':'Month'}, inplace=True)
dataset.head(10)

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,year,month,day
0,12,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,1007.1,8.0,NaN,16.9,21.8,No,No,2008,12,1
1,12,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,1007.8,NaN,NaN,17.2,24.3,No,No,2008,12,2
2,12,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,1008.7,NaN,2.0,21.0,23.2,No,No,2008,12,3
3,12,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,1012.8,NaN,NaN,18.1,26.5,No,No,2008,12,4
4,12,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,1006.0,7.0,8.0,17.8,29.7,No,No,2008,12,5
5,12,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,1005.4,NaN,NaN,20.6,28.9,No,No,2008,12,6
6,12,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,1008.2,1.0,NaN,18.1,24.6,No,No,2008,12,7
7,12,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,1010.1,NaN,NaN,16.3,25.5,No,No,2008,12,8
8,12,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,1003.6,NaN,NaN,18.3,30.2,No,Yes,2008,12,9
9,12,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,1005.7,NaN,NaN,20.1,28.2,Yes,No,2008,12,10

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 26 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Month          145460 non-null  int64
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
 23  year           145460 non-null  int64
 24  month          145460 non-null  int64
 25  day            145460 non-null  int64
dtypes: float64(16), int64(4), object(6)
memory usage: 28.9+ MB

# encoding categorical and numerical data

In [9]:
categorical_features = [column_name for column_name in dataset.columns if dataset[column_name].dtype == 'O']
dataset[categorical_features].isnull().sum()

Location            0
WindGustDir     10326
WindDir9am      10566
WindDir3pm       4228
RainToday        3261
RainTomorrow     3267
dtype: int64

In [10]:
categorical_features_with_null = [feature for feature in categorical_features if dataset[feature].isnull().sum()]
for each_feature in categorical_features_with_null:
    mode_val = dataset[each_feature].mode()[0]
    dataset[each_feature].fillna(mode_val,inplace=True)

In [11]:
numerical_features = [column_name for column_name in dataset.columns if dataset[column_name].dtype != 'O']
dataset[numerical_features].isnull().sum()

Month                0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustSpeed    10263
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
year                 0
month                0
day                  0
dtype: int64

In [12]:
numerical_features_with_null = [feature for feature in numerical_features if dataset[feature].isnull().sum()]
for feature in numerical_features_with_null:
    mean_value = dataset[feature].mean()
    dataset[feature].fillna(mean_value,inplace=True)

In [13]:
def encode_data(feature_name):

    mapping_dict = {}

    unique_values = list(dataset[feature_name].unique())

    for idx in range(len(unique_values)):

        mapping_dict[unique_values[idx]] = idx

    return mapping_dict

dataset['RainToday'].replace({'No':0, 'Yes': 1}, inplace = True)

dataset['RainTomorrow'].replace({'No':0, 'Yes': 1}, inplace = True)

dataset['WindGustDir'].replace(encode_data('WindGustDir'),inplace = True)

dataset['WindDir9am'].replace(encode_data('WindDir9am'),inplace = True)

dataset['WindDir3pm'].replace(encode_data('WindDir3pm'),inplace = True)

dataset['Location'].replace(encode_data('Location'), inplace = True)

In [14]:
corr = dataset.corr()
corr.style.background_gradient(cmap='coolwarm')

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 26 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Month          145460 non-null  int64
 1   Location       145460 non-null  int64
 2   MinTemp        145460 non-null  float64
 3   MaxTemp        145460 non-null  float64
 4   Rainfall       145460 non-null  float64
 5   Evaporation    145460 non-null  float64
 6   Sunshine       145460 non-null  float64
 7   WindGustDir    145460 non-null  int64
 8   WindGustSpeed  145460 non-null  float64
 9   WindDir9am     145460 non-null  int64
 10  WindDir3pm     145460 non-null  int64
 11  WindSpeed9am   145460 non-null  float64
 12  WindSpeed3pm   145460 non-null  float64
 13  Humidity9am    145460 non-null  float64
 14  Humidity3pm    145460 non-null  float64
 15  Pressure9am    145460 non-null  float64
 16  Pressure3pm    145460 non-null  float64
 17  Cloud9am       145460 non-null  float64
 18  Cloud3pm       145460 non-null  float64
 19  Temp9am        145460 non-null  float64
 20  Temp3pm        145460 non-null  float64
 21  RainToday      145460 non-null  int64
 22  RainTomorrow   145460 non-null  int64
 23  year           145460 non-null  int64
 24  month          145460 non-null  int64
 25  day            145460 non-null  int64
dtypes: float64(16), int64(10)
memory usage: 28.9 MB

In [16]:
dataset = dataset.drop(['Evaporation', 'Sunshine', 'Cloud9am', 'Cloud3pm'], axis = 1)

In [17]:
dataset.head(10)

,Month,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,year,month,day
0,12,0,13.4,22.9,0.6,0,44.0,0,0,20.0,...,22.0,1007.7,1007.1,16.9,21.8,0,0,2008,12,1
1,12,0,7.4,25.1,0.0,1,44.0,1,1,4.0,...,25.0,1010.6,1007.8,17.2,24.3,0,0,2008,12,2
2,12,0,12.9,25.7,0.0,2,46.0,0,1,19.0,...,30.0,1007.6,1008.7,21.0,23.2,0,0,2008,12,3
3,12,0,9.2,28.0,0.0,3,24.0,2,2,11.0,...,16.0,1017.6,1012.8,18.1,26.5,0,0,2008,12,4
4,12,0,17.5,32.3,1.0,0,41.0,3,3,7.0,...,33.0,1010.8,1006.0,17.8,29.7,0,0,2008,12,5
5,12,0,14.6,29.7,0.2,1,56.0,0,4,19.0,...,23.0,1009.2,1005.4,20.6,28.9,0,0,2008,12,6
6,12,0,14.3,25.0,0.0,0,50.0,4,4,20.0,...,19.0,1009.6,1008.2,18.1,24.6,0,0,2008,12,7
7,12,0,7.7,26.7,0.0,0,35.0,5,4,6.0,...,19.0,1013.4,1010.1,16.3,25.5,0,0,2008,12,8
8,12,0,9.7,31.9,0.0,4,80.0,2,3,7.0,...,9.0,1008.9,1003.6,18.3,30.2,0,1,2008,12,9
9,12,0,13.1,30.1,1.4,0,28.0,6,5,15.0,...,27.0,1007.0,1005.7,20.1,28.2,1,0,2008,12,10

In [18]:
X = dataset[['Month','Location','MinTemp','MaxTemp','Rainfall','RainToday']]
Y = dataset['RainTomorrow']

# splitting dataset into traing and testing

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.15, random_state = 0)

In [20]:
x_train

        Month  Location  MinTemp  MaxTemp  Rainfall  RainToday
96460      11        32     15.7     22.2       1.4          1
81232       8        27      7.5     16.3       6.0          1
72188       2        23     11.7     28.9       0.0          0
138535     11        45     23.1     38.1       0.0          0
71686       8        23      7.3     18.2       0.4          0
...       ...       ...      ...      ...       ...        ...
41993      12        13     17.8     38.1       0.0          0
97639       3        32     12.5     27.3       0.0          0
95939       6        31     17.0     29.8       0.0          0
117952     11        39     11.9     22.0       3.8          1
43567      10        14     12.0     16.7       0.8          0

[123641 rows x 6 columns]

# feature scaling

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)

In [22]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0,C=1.0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [23]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
print("testing score")
print(classifier.score(x_test,y_test))
print('\r')
print("traing score")
print(classifier.score(x_train,y_train))

testing score
0.8022824144094597

traing score
0.8050970147443001

In [25]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
cm

array([[16321,   685],
       [ 3629,  1184]], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8022824144094597

# K-Nearest Neighbor(KNN)

In [27]:
from sklearn.neighbors import KNeighborsClassifier  
classifier1= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier1.fit(x_train, y_train)

KNeighborsClassifier()

In [28]:
y_pred= classifier1.predict(x_test)

# overfitting in K-Nearest Neighbor algoritm

In [29]:
print("testing score")
print(classifier1.score(x_test,y_test))
print('\r')
print("traing score")
print(classifier1.score(x_train,y_train))

testing score
0.787982950639351

traing score
0.8457712247555422

# support vector machine

In [35]:
from sklearn.tree import DecisionTreeClassifier
classifier2= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [36]:
y_pred= classifier2.predict(x_test)

# overfitting in decisiontreeclassifier

In [40]:
print("testing score")
print(classifier2.score(x_test,y_test))
print('\r')
print("traing score")
print(classifier2.score(x_train,y_train))

testing score
0.73133507493469

traing score
0.9988110739964898

In [ ]:
overRandomForestClassifier

In [42]:
from sklearn.ensemble import RandomForestClassifier  
classifier3= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier3.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [43]:
print("testing score")
print(classifier3.score(x_test,y_test))
print('\r')
print("traing score")
print(classifier3.score(x_train,y_train))

testing score
0.7935744076263807

traing score
0.9790846078566171

In [44]:
import pickle

In [45]:
myfile= 'myfile_model.sav'
pickle.dump(classifier, open(myfile, 'wb'))

In [46]:
model=pickle.load(open('myfile_model.sav','rb'))

In [47]:
model.predict([[10,18,6.4,10.9,38.0,1]])

array([1], dtype=int64)

In [48]:
x_train

array([[ 1.34354502,  0.60684589,  0.55070589, -0.14282713, -0.11547843,
         1.8849377 ],
       [ 0.46784874,  0.24809531, -0.73727917, -0.97533892,  0.43149014,
         1.8849377 ],
       [-1.28354384, -0.03890515, -0.0775795 ,  0.80256761, -0.28194712,
        -0.53052151],
       ...,
       [-0.11594879,  0.53509577,  0.75489865,  0.92956093, -0.28194712,
        -0.53052151],
       [ 1.34354502,  1.10909669, -0.04616523, -0.17104787,  0.16989648,
         1.8849377 ],
       [ 1.05164626, -0.68465618, -0.0304581 , -0.91889744, -0.18682215,
        -0.53052151]])

In [49]:
pred=model.predict(x_train)

In [62]:
pred[22]

0

In [63]:
count=0
for i in pred:
    count=count+1
    if i == 1:
        print(count)
        break

147

In [64]:
df=pd.DataFrame(x_train)

In [68]:
df.head(147)

        Month  Location  MinTemp  MaxTemp  Rainfall  RainToday
96460      11        32     15.7     22.2       1.4          1
81232       8        27      7.5     16.3       6.0          1
72188       2        23     11.7     28.9       0.0          0
138535     11        45     23.1     38.1       0.0          0
71686       8        23      7.3     18.2       0.4          0
...       ...       ...      ...      ...       ...        ...
95545       5        31     14.5     29.0       0.0          0
136489      1        45     21.2     38.8       0.0          0
122039      6        40     11.6     19.6       7.6          1
100710      4        33     10.3     19.2       0.0          0
57876      10        18      6.4     10.9      38.0          1

[147 rows x 6 columns]

In [ ]:
10,18,6.4,10.9,38.0,1